### ISSUE TITLE
SynapseAPI Crash : Out of bound

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/SynapseAPI#13]
Hello,
Synapse works for a few minutes but after I get this error ;

> java.lang.ArrayIndexOutOfBoundsException: 0
>     at org.itxtech.synapseapi.SynapseAPI.getPacket(SynapseAPI.java:254)
>     at org.itxtech.synapseapi.SynapseAPI.handleDataPacket(SynapseAPI.java:336)
>     at org.itxtech.synapseapi.network.SynapseInterface.handlePacket(SynapseInterface.java:79)
>     at org.itxtech.synapseapi.network.SynapseInterface.process(SynapseInterface.java:53)
>     at org.itxtech.synapseapi.SynapseAPI.tick(SynapseAPI.java:236)
>     at org.itxtech.synapseapi.SynapseAPI$Ticker.run(SynapseAPI.java:206)
>     at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
>     at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:198)
>     at cn.nukkit.Server.tick(Server.java:991)
>     at cn.nukkit.Server.tickProcessor(Server.java:785)
>     at cn.nukkit.Server.start(Server.java:765)
>     at cn.nukkit.Server.<init>(Server.java:456)
>     at cn.nukkit.Nukkit.main(Nukkit.java:65)

Thanks

**Comment by Creeperface01** [comment]
@boybook also > 13:51:32 [CRITICAL] Exception while invoking run
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1050)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1036)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3859)
	at cn.nukkit.command.CommandReader.unstashLine(CommandReader.java:102)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:155)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:141)
	at cn.nukkit.utils.MainLogger.info(MainLogger.java:87)
	at cn.nukkit.Player.close(Player.java:3189)
	at cn.nukkit.Player.close(Player.java:3127)
	at org.itxtech.synapseapi.SynapseAPI.handleDataPacket(SynapseAPI.java:362)
	at org.itxtech.synapseapi.network.SynapseInterface.handlePacket(SynapseInterface.java:79)
	at org.itxtech.synapseapi.network.SynapseInterface.process(SynapseInterface.java:53)
	at org.itxtech.synapseapi.SynapseAPI.tick(SynapseAPI.java:251)
	at org.itxtech.synapseapi.SynapseAPI$Ticker.run(SynapseAPI.java:221)
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:98)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:197)
	at cn.nukkit.Server.tick(Server.java:975)
	at cn.nukkit.Server.tickProcessor(Server.java:776)
	at cn.nukkit.Server.start(Server.java:756)
	at cn.nukkit.Server.<init>(Server.java:452)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)
