### ISSUE TITLE
disconnect bug

### ISSUE THREAD

**Issue by Creeperface01** [iTXTech/SynapseAPI#15]
15:41:39 [NOTICE] [SynapseAPI] Synapse Client has disconnected due to timeout

> 15:41:39 [NOTICE] Trying to re-connect to Synapse Server

> 15:41:39 [INFO] CreeperFace[/193.85.210.132:19132] logged out due to Server Closed
15:41:39 [NOTICE] SynapseAPI has connected to e.gameteam.cz:10305
  
> 15:41:39 [CRITICAL] Exception while invoking run
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
	at jline.console.ConsoleReader.backspace(ConsoleReader.java:1050)
	at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1036)
	at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3859)
	at cn.nukkit.command.CommandReader.unstashLine(CommandReader.java:102)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:155)
	at cn.nukkit.utils.MainLogger.send(MainLogger.java:141)
	at cn.nukkit.utils.MainLogger.info(MainLogger.java:87)
	at cn.nukkit.Player.close(Player.java:3292)
	at cn.nukkit.Player.close(Player.java:3230)
	at org.itxtech.synapseapi.SynapseAPI.handleDataPacket(SynapseAPI.java:362)
	at org.itxtech.synapseapi.network.SynapseInterface.handlePacket(SynapseInterface.java:79)
	at org.itxtech.synapseapi.network.SynapseInterface.process(SynapseInterface.java:53)
	at org.itxtech.synapseapi.SynapseAPI.tick(SynapseAPI.java:251)
	at org.itxtech.synapseapi.SynapseAPI$Ticker.run(SynapseAPI.java:221)
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:98)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:197)
	at cn.nukkit.Server.tick(Server.java:975)
	at cn.nukkit.Server.tickProcessor(Server.java:776)
	at cn.nukkit.Server.start(Server.java:756)
	at cn.nukkit.Server.<init>(Server.java:452)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

> 15:41:40 [NOTICE] [SynapseAPI] Connecting e.gameteam.cz:10305

> 15:41:40 [NOTICE] [SynapseAPI] Login success to e.gameteam.cz:10305

**Comment by Creeperface01** [comment]
also this happens quite often:
18:26:16 [NOTICE] [SynapseAPI] Synapse Client has disconnected due to timeout

> 18:26:16 [INFO] CreeperFace[/193.165.24.1:19132] logged out due to Server Closed

> 18:26:16 [NOTICE] Trying to re-connect to Synapse Server

> 18:26:16 [NOTICE] SynapseAPI has connected to e.gameteam.cz:10305

> quit task
1
18:26:16 [NOTICE] [SynapseAPI] Connecting e.gameteam.cz:10305

> 18:26:16 [NOTICE] [SynapseAPI] Login success to e.gameteam.cz:10305

**Comment by Creeperface01** [comment]
@boybook any solution?

**Comment by File14** [comment]
I don't have this issuse.

**Comment by Creeperface01** [comment]
Ive just noticed i have 1 month old synapse :D

**Comment by matiszefCZ** [comment]
lol gameteam ? xD
