### ISSUE TITLE
Bug transfer

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/SynapseAPI#25]
SynapseAPI not work. If you transfer to other server ,not work to move or break. @boybook @PeratX 

And have and one error in console:
14:42:02 [ALERT] java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
at org.itxtech.synapseapi.SynapsePlayer.doFirstSpawn(SynapsePlayer.java:393)
at cn.nukkit.Player.sendNextChunk(Player.java:671)
at cn.nukkit.Player.checkNetwork(Player.java:1483)
at cn.nukkit.Server.tick(Server.java:1003)
at cn.nukkit.Server.tickProcessor(Server.java:786)
at cn.nukkit.Server.start(Server.java:765)
at cn.nukkit.Server.(Server.java:456)
at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by boybook** [comment]
Please use the latest version of SynapseAPI and Nemisys for 0.16.

**Comment by NycuRO** [comment]
@boybook Fixed,thanks.
