### ISSUE TITLE
Bug transfer

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/SynapseAPI#33]
If you transfered ,get this error : @boybook 

19:34:53 [CRITICAL] Could not execute taskHandler 1: org.itxtech.synapseapi.SynapsePlayer.sendAttributes(Z)V
19:34:53 [ALERT] java.lang.RuntimeException: java.lang.NoSuchMethodError: org.itxtech.synapseapi.SynapsePlayer.sendAttributes(Z)V
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:207)
        at cn.nukkit.Server.tick(Server.java:990)
        at cn.nukkit.Server.tickProcessor(Server.java:789)
        at cn.nukkit.Server.start(Server.java:768)
        at cn.nukkit.Server.<init>(Server.java:459)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.NoSuchMethodError: org.itxtech.synapseapi.SynapsePlayer.sendAttributes(Z)V
        at org.itxtech.synapseapi.SynapsePlayer.processLogin(SynapsePlayer.java:259)
        at cn.nukkit.Player.authenticateCallback(Player.java:1646)
        at cn.nukkit.Player.tryAuthenticate(Player.java:1635)
        at cn.nukkit.Player.onPlayerPreLogin(Player.java:1628)
        at cn.nukkit.Player.handleDataPacket(Player.java:1961)
        at org.itxtech.synapseapi.SynapsePlayer.handleDataPacket(SynapsePlayer.java:434)
        at org.itxtech.synapseapi.SynapsePlayer.handleLoginPacket(SynapsePlayer.java:63)
        at org.itxtech.synapseapi.SynapseEntry.handleDataPacket(SynapseEntry.java:280)
        at org.itxtech.synapseapi.network.SynapseInterface.handlePacket(SynapseInterface.java:79)
        at org.itxtech.synapseapi.network.SynapseInterface.process(SynapseInterface.java:53)
        at org.itxtech.synapseapi.SynapseEntry.tick(SynapseEntry.java:204)
        at org.itxtech.synapseapi.SynapseEntry$Ticker.run(SynapseEntry.java:174)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:204)
        ... 5 more

**Comment by boybook** [comment]
Please use the latest version of Nukkit.
