### ISSUE TITLE
NPE on join

### ISSUE THREAD

**Issue by Creeperface01** [iTXTech/SynapseAPI#35]
2016-11-23 16:04:42 [ALERT] java.lang.NullPointerException
	at org.itxtech.synapseapi.SynapsePlayer.dataPacket(SynapsePlayer.java:472)
	at cn.nukkit.Player.dataPacket(Player.java:884)
	at cn.nukkit.Player.sendChunk(Player.java:638)
	at cn.nukkit.level.Level.sendChunkFromCache(Level.java:2276)
	at cn.nukkit.level.Level.chunkRequestCallback(Level.java:2320)
	at cn.nukkit.level.Level.chunkRequestCallback(Level.java:2311)
	at cn.nukkit.level.format.mcregion.McRegion.requestChunkTask(McRegion.java:173)
	at cn.nukkit.level.Level.processChunkRequest(Level.java:2300)
	at cn.nukkit.level.Level.doTick(Level.java:784)
	at cn.nukkit.Server.checkTickUpdates(Server.java:918)
	at cn.nukkit.Server.tick(Server.java:993)
	at cn.nukkit.Server.tickProcessor(Server.java:789)
	at cn.nukkit.Server.start(Server.java:768)
	at cn.nukkit.Server.<init>(Server.java:459)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

2016-11-23 16:04:42 [CRITICAL] Could not tick level "lobby": java.lang.NullPointerException
2016-11-23 16:04:42 [ALERT] java.lang.NullPointerException
	at org.itxtech.synapseapi.SynapsePlayer.dataPacket(SynapsePlayer.java:472)
	at cn.nukkit.Player.dataPacket(Player.java:884)
	at cn.nukkit.Player.sendChunk(Player.java:638)
	at cn.nukkit.level.Level.sendChunkFromCache(Level.java:2276)
	at cn.nukkit.level.Level.chunkRequestCallback(Level.java:2320)
	at cn.nukkit.level.Level.chunkRequestCallback(Level.java:2311)
	at cn.nukkit.level.format.mcregion.McRegion.requestChunkTask(McRegion.java:173)
	at cn.nukkit.level.Level.processChunkRequest(Level.java:2300)
	at cn.nukkit.level.Level.doTick(Level.java:784)
	at cn.nukkit.Server.checkTickUpdates(Server.java:918)
	at cn.nukkit.Server.tick(Server.java:993)
	at cn.nukkit.Server.tickProcessor(Server.java:789)
	at cn.nukkit.Server.start(Server.java:768)
	at cn.nukkit.Server.<init>(Server.java:459)
	at cn.nukkit.Nukkit.main(Nukkit.java:65)

this happens when more players join at the same time.

**Comment by File14** [comment]
Could not tick level "lobby": java.lang.NullPointerException

**Comment by Creeperface01** [comment]
i can read...

**Comment by Creeperface01** [comment]
its nukkit's message
