### ISSUE TITLE
Error || Plugin wont work for the newest!

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/SynapseAPI#38]
HEllo folks, the plugin SynapseAPI wont work for the nukkit 1.0 [https://github.com/Nukkit/Nukkit/tree/1.0.0]
Here is the error hopefully you fix it as soon as possible!
Error:
2017-1-8 07:40:58 [EMERGENCY] Exception happened while ticking server
2017-1-8 07:40:58 [ALERT] java.lang.NoSuchMethodError: org.itxtech.synapseapi.SynapsePlayer.getHealth()I
	at org.itxtech.synapseapi.SynapsePlayer.doFirstSpawn(SynapsePlayer.java:387)
	at cn.nukkit.Player.sendNextChunk(Player.java:733)
	at cn.nukkit.Player.checkNetwork(Player.java:1605)
	at cn.nukkit.Server.tick(Server.java:1002)
	at cn.nukkit.Server.tickProcessor(Server.java:791)
	at cn.nukkit.Server.start(Server.java:770)
	at cn.nukkit.Server.<init>(Server.java:461)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-1-8 07:40:58 [ALERT] 
"SynLib Thread #30" Id=30 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at org.itxtech.synapseapi.network.synlib.Session.tickProcessor(Session.java:65)
	at org.itxtech.synapseapi.network.synlib.Session.run(Session.java:45)
	at org.itxtech.synapseapi.network.synlib.Session.<init>(Session.java:41)
	at org.itxtech.synapseapi.network.synlib.SynapseClient.run(SynapseClient.java:119)

"Abandoned connection cleanup thread" Id=29 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@31add175
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@31add175
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

"process reaper" Id=28 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@ae3540e
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@ae3540e
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #5" Id=27 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #4" Id=26 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #3" Id=25 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #2" Id=24 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #1" Id=23 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@600b9d27
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Abandoned connection cleanup thread" Id=22 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@3688eb5b
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3688eb5b
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

"nioEventLoopGroup-2-1" Id=19 RUNNABLE (in native)
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@69f1a286
	-  locked java.util.Collections$UnmodifiableSet@7922d892
	-  locked sun.nio.ch.EPollSelectorImpl@457c9034
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	...

"RakNet Thread #16" Id=16 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
	at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
	at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"RCON" Id=15 RUNNABLE (in native)
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked sun.nio.ch.Util$2@345f69f3
	-  locked java.util.Collections$UnmodifiableSet@50de186c
	-  locked sun.nio.ch.EPollSelectorImpl@3f57bcad
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at cn.nukkit.network.rcon.RCONServer.run(RCONServer.java:84)

"Console" Id=10 RUNNABLE (in native)
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	-  locked jline.internal.NonBlockingInputStream@1e8b7643
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
	-  locked jline.internal.NonBlockingInputStream@1e8b7643
	at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
	-  locked jline.internal.NonBlockingInputStream@1e8b7643
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136)
	...

"NonBlockingInputStreamThread" Id=14 WAITING on jline.internal.NonBlockingInputStream@1e8b7643 owned by "Console" Id=10
	at java.lang.Object.wait(Native Method)
	-  waiting on jline.internal.NonBlockingInputStream@1e8b7643
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	at java.lang.Thread.run(Thread.java:745)

"Thread-0" Id=9 TIMED_WAITING on cn.nukkit.utils.MainLogger@51549490
	at java.lang.Object.wait(Native Method)
	-  waiting on cn.nukkit.utils.MainLogger@51549490
	at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:222)
	at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@71e9ebae
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@71e9ebae
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@73d983ea
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@73d983ea
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" Id=1 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:110)
	at cn.nukkit.Server.tickProcessor(Server.java:805)
	at cn.nukkit.Server.start(Server.java:770)
	at cn.nukkit.Server.<init>(Server.java:461)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by SupremeMortal** [comment]
Could you put the code in a pastebin/hastebin next time like this:

**Comment by JackboyPlay** [comment]
@boybook please fix it :(

**Comment by boybook** [comment]
Yes, I will fix it.

**Comment by boybook** [comment]
You can compile this plugin base of the latest version of Nukkit to fix this problem.

**Comment by JackboyPlay** [comment]
@boybook when did you fix it?

**Comment by Creeperface01** [comment]
Sorry :D

**Comment by vzlomka76** [comment]
@boybook when did you fix it? i can't download new version because i have pocketmine servers (SynapsePM doesn't work on Synapse protocol 8)

**Comment by Creeperface01** [comment]
Its fixed... Recompile it
